### ISSUE TITLE
ios10 以下使用flex布局，子元素使用absolute定位错位

### ISSUE THREAD

**Issue by Iscrj** [Iscrj/xiaochengxu#2]
### 问题描述
最近开发过程中遇到 flex 配合 position 布局，IOS10< (IOS11 没有测试)，会发生布局错位。
具体情况如下：

```html
<style lang="less">
.flex-container{
    position: relative;
    width: 40px;
    height: 40px;
    padding: 8px;
    background: rgb(0, 153, 255);
    box-shadow: rgb(102, 102, 102) 0px 2px 8px;
    display: flex;
    align-items: center;
    justify-content: center;
    .flex-wrapper{
        background: red;
        position: absolute;
        width: 50%;
        height: 50%; 
    }
}
</style>

<div class="flex-container">
   <div class="flex-wrapper"> 
   </div>
</div> 

```
正常效果如下

![正常效果](static/imgs/issues/flex.png)

IOS10 效果

![IOS10 效果](static/imgs/issues/flex-ios10.png)

错位了！

蓝色背景是父元素，红色是需要居中定位的子元素。 

### 解决方案

我反复测试， 简单的解决办法，就是去除 `position: absolute`; 如果子元素必须绝对定位的，我建议不再采用flex的居中方案， 可以使用以下居中方案

绝对定位 + transform
```css
.flex-wrapper{
        background: red;
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        width: 50%;
        height: 50%;  
}
```

绝对定位 + margin

```css
.flex-wrapper{
        background: red;
        position: absolute; 
        top: 0;
        bottom: 0;
        left: 0;
        right: 0;
        margin: auto;
        width: 50%;
        height: 50%; 
}
```

其它兼容性较好的居中解决方案（可自行百度）

**建议： flex布局的子元素不使用绝对定位，使用其他的替代方案**
